x-defaults: &defaults
  restart: unless-stopped

services:
  flask-server:
    build: .
    container_name: flask-server
    ports:
      - "60000:60000"
    volumes:
      - ./:/app
    <<: *defaults 